apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acmeair
      tier: haproxy
  template:
    metadata:
      annotations:
        vpa.k8s.io/in-place-update-policy: "true"
      labels:
        app: acmeair
        tier: haproxy
    spec:
      containers:
        - name: haproxy-container
          image: rpizziol/acmeair-proxy:0.24
          imagePullPolicy: Always
          resizePolicy:
            - resourceName: cpu
              restartPolicy: NotRequired
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8080
